#!/usr/bin/env bash

set -eu

mydir=$(dirname "$0")
basedir="$mydir/../"
hook=$(basename "$0")
git_dir=$(git rev-parse --show-toplevel)
. "$basedir/lib/common"

load_env "$basedir"

if [ -z "${GHOOKS_CORE_DIRENV_LOADED:-}" -a "$(load_config core.direnv)" = "true" ]; then
	GHOOKS_CORE_DIRENV_LOADED=true direnv exec "$git_dir" "$0" "$@"
	exit
fi

echo 'begin: ghooks'
list_apps | while read app || test -n "$app"
do
	has_script=''
	while read script || test -n "$script"
	do
		if [ -z "$has_script" ]; then
			echo "begin: $app"
			has_script="1"
		fi
		
		run_script "$script" "$hook" "$@"
	done < <(get_app_hook "$app" "$hook")
	if [ -n "$has_script" ]; then
		echo "done: $app"
	fi
done
echo 'done: ghooks'
