#!/usr/bin/env bash

set -eu

mydir=$(dirname "$0")
basedir="$mydir/.."
. "$basedir/lib/common"

load_env "$basedir"
default_apps_file="$GHOOKS_BASEDIR/setup/default-apps"

function setup() {
    cat "$default_apps_file" | grep -ve '^#' -e '^$' | while read line || test -n "$line"
    do
        src_app_path="$GHOOKS_BASEDIR/$line"
        install_app "$src_app_path" || :
    done
    install_git_config
}

function install_from_collection() {
    local app_name="$1"
    local app_path="$GHOOKS_BASEDIR/collection/$app_name"

    test -d "$app_path" || {
        echo "$app_name not found in collection." >&2
        return 1
    }

    install_app "$app_path"
}

case "${1:-}" in
"")
    setup
    ;;
"--setup")
    setup
    ;;
"--refresh")
    refresh_apps
    ;;
*)
    install_from_collection "$1"
esac
