#!/usr/bin/env bash

set -eu

basedir=$(cd $(dirname $(dirname $0)) && pwd)

lib_dir="$basedir/lib/"
hooks_dir="$basedir/hooks/"
custom_hooks_dir="$basedir/custom-hooks/"

hook_base_file="$lib_dir/hook-base"
hook_types_file="$basedir/setup/hook-types"

function load_hooktypes() {
    cat "$hook_types_file" | grep -v -e '^#' -e '^\s*$'
}

echo "create dir: \"$hooks_dir\""
mkdir -p "$hooks_dir"
load_hooktypes | while read line || test -n "$line"
do
    echo "create dir: \"$custom_hooks_dir/$line\""
    mkdir -p "$custom_hooks_dir/$line"

    echo "create: \"$hooks_dir/$line\""
    cat > "$hooks_dir/$line" <<EOF
#!/usr/bin/env bash
hook_base_file="\$(dirname \$(dirname \$0))/lib/hook-base"
. "\$hook_base_file"
EOF
    chmod +x "$hooks_dir/$line"
done

echo "change git config(global): core.hooksPath \"$hooks_dir\""
git config --global core.hooksPath "$hooks_dir"
